env {
  execution.parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
    Jdbc {
        plugin_output = "fake"
        url = "jdbc:mysql://35.46.5.36:3306/vrc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100000
        user = "root"
        password = "HTcf2022!@#"
        query = "SELECT 
			 CONCAT(device_no,DATE_FORMAT(biz_time, '_%Y%m%d%H0000')) AS id,
			 device_no AS deviceNo,
       direction,
       SUM(vehicle_nums) AS vehicleNums,
       DATE_FORMAT(biz_time, '%Y-%m-%d %H:00:00') AS bizTime
FROM t_statistics_info_min_202504
WHERE
    biz_time >= DATE_FORMAT(NOW(), '%Y-%m-%d %H:00:00')
    AND biz_time < DATE_ADD(DATE_FORMAT(NOW(), '%Y-%m-%d %H:00:00'), INTERVAL 1 HOUR)
GROUP BY bizTime, deviceNo"
    }
}


transform {
  FieldMapper {
    plugin_input = "fake"
    plugin_output = "fake1"
    field_mapper = {
      id = id
      deviceNo = deviceNo
      direction = direction
      vehicleNums = vehicleNums
      bizTime = bizTime
    }
  }
}

sink {
   ConsoleSink {
       plugin_input = "fake1"
   }
}